<html>
<head>
    <title>This Email generated by cybexo.com</title>
</head>
<body>
    <h1>{{ $user->username }}</h1>
    <h1>Your OTP for forget password is: </h1>
    <h1>{{ $user->token }}</h1>
    <p>Thank you</p>
</body>
</html> 